name: CI/CD workflow of application server side

on:
  push:
    branches:
      - main

jobs:
  backend:
    name: Build and deploy the application server side
    runs-on: ubuntu-latest
    env:
      MONGO_DB_USERNAME: ${{ MONGO_DB_USERNAME }}
      MONGO_DB_PASSWORD: ${{ MONGO_DB_PASSWORD }}
      MONGO_DB_URI: ${{ MONGO_DB_URI }}
      JWT_SECRET: ${{ JWT_SECRET }}
      JWT_EXPIRATION: ${{ JWT_EXPIRATION }}
      JWT_ISSUER: ${{ JWT_ISSUER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 21

      - name: Run Unit tests
        run: |
          cd couchsurfing-backend
          mvn -B test --file pom.xml

      - name: Build the application
        run: |
          cd couchsurfing-backend
          mvn clean
          mvn -B package --file pom.xml

      - name: Get short commit hash
        id: vars
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/couchsurfing-api:${{ env.COMMIT_HASH }}

      - name: Login to Dockerhub
        uses:  docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/couchsurfing-api:${{ env.COMMIT_HASH }}
